name: Testes E2E BugBank

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testes-playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest 

    # 3. O PASSO A PASSO
    steps:
    - name: Pegar o código do repositório
      uses: actions/checkout@v4

    - name: Instalar o NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Instalar dependências do projeto (npm install)
      run: npm ci

    - name: Instalar os navegadores do Playwright
      run: npx playwright install --with-deps

    - name: Rodar os testes automatizados! 🚀
      run: npx playwright test

    - name: Salvar relatório HTML
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30